### ISSUE TITLE
出现 问题

### ISSUE THREAD

**Issue by woodguo** [Zydiii/OpenGL_FinalProject#1]
1、无法打开  元数据 文件
2、无法使用/ZW编译C文件
请问是哪里配置的不对吗，可以帮忙解决下吗？速求  找遍了网络 没有办法了  才来这里留言 @Zydiii 
我的微信  15648883585

**Comment by Zydiii** [comment]
请问有运行结果报错截图吗？我好像没有遇到这样的问题

**Comment by woodguo** [comment]
&nbsp;啊！终于有人可以回应我这个问题了。先谢谢你 。
我的vs2019&nbsp; 配了一下依赖&nbsp;不可以，然后我把vs2019&nbsp;全部更新&nbsp;以及升级&nbsp; 还是不可以。&nbsp;
最后我把vs卸载再安装 。可是还是这俩问题，唯一的不同是，&nbsp;现在我找别的代码去跑，也出现这俩问题。。。好似他俩成为了寄生虫，寄生在我的电脑上。&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zydiii"<notifications@github.com&gt;; 
发送时间: 2020年4月8日(星期三) 下午4:32
收件人: "Zydiii/OpenGL_FinalProject"<OpenGL_FinalProject@noreply.github.com&gt;; 
抄送: "780665068"<780665068@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Zydiii/OpenGL_FinalProject] 出现 问题 (#1)





 
请问有运行结果报错截图吗？我好像没有遇到这样的问题

**Comment by Zydiii** [comment]
我没有遇到类似这两个报错哎。。是运行任何项目都不可以吗？看起来像vs自身的配置问题。

**Comment by woodguo** [comment]
哎呀，看来是的呢。&nbsp;好想用你的程序&nbsp;跑出来玩玩 。
&nbsp;请问你有时间可以帮我弄下你的程序吗。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zydiii"<notifications@github.com&gt;; 
发送时间: 2020年4月8日(星期三) 下午4:50
收件人: "Zydiii/OpenGL_FinalProject"<OpenGL_FinalProject@noreply.github.com&gt;; 
抄送: "780665068"<780665068@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Zydiii/OpenGL_FinalProject] 出现 问题 (#1)





 
我没有遇到类似这两个报错哎。。是运行任何项目都不可以吗？看起来像vs自身的配置问题。

**Comment by Zydiii** [comment]
抱歉，不是我项目的问题我也没有办法解决，不好意思

**Comment by woodguo** [comment]
你好&nbsp;我再请教下可以吗，你那个程序。&nbsp;是配置好&nbsp;glfw&nbsp;和glad&nbsp;就可以了吗？&nbsp; 有什么特别需要注意的地方吗？&nbsp; 我反复读了你的说明书了。&nbsp; 很喜欢你的程序。&nbsp;请务必稍微讲解下&nbsp; 谢谢你&nbsp; 占用你时间了&nbsp; 谢谢你、

**Comment by Zydiii** [comment]
release里面的exe如果能双击运行说明显卡这些没有什么问题，然后vs项目我其实是配置好了的，所有依赖文件都添加进了vs的配置里面，正常来说双击.sln是可以直接运行的。
但是可能不同的电脑会有不同的问题，所以如果有报错可能还需要按照报错重新配置一下环境的，把Libraries文件夹下面的依赖文件在vs里进行对应的配置试试
